# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waypoints.proto
# Protobuf Python Version: 4.25.9
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwaypoints.proto\x12\ttelemetry\"1\n\x08Waypoint\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x0b\n\x03yaw\x18\x03 \x01(\x01\"L\n\x0cWaypointList\x12&\n\twaypoints\x18\x01 \x03(\x0b\x32\x13.telemetry.Waypoint\x12\x14\n\x0ctimestamp_ns\x18\x02 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'waypoints_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WAYPOINT']._serialized_start=30
  _globals['_WAYPOINT']._serialized_end=79
  _globals['_WAYPOINTLIST']._serialized_start=81
  _globals['_WAYPOINTLIST']._serialized_end=157
# @@protoc_insertion_point(module_scope)
